# Generated by Django 2.0.2 on 2018-02-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='categories',
            field=models.ManyToManyField(null=True, to='posts.Category'),
        ),
        migrations.AlterField(
            model_name='whisper',
            name='categories',
            field=models.ManyToManyField(null=True, to='posts.Category'),
        ),
    ]
