# Generated by Django 2.0.2 on 2018-02-05 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180204_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='whisper',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whisper', to='accounts.Profile'),
        ),
    ]
