# Generated by Django 2.0.2 on 2018-02-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20180210_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whisper',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
