# Generated by Django 2.0.2 on 2018-02-04 14:18

import accounts.names
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default=accounts.names.generate_nickname, max_length=80),
        ),
    ]
